# Generated by Django 2.0.7 on 2020-01-14 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('Api_type', models.IntegerField(default=1, verbose_name='test/config')),
                ('Api_name', models.CharField(max_length=50, verbose_name='接口/配置名称')),
                ('belong_project', models.CharField(max_length=50, verbose_name='所属项目')),
                ('Api_include', models.CharField(max_length=1024, null=True, verbose_name='前置config/test')),
                ('Api_author', models.CharField(max_length=20, verbose_name='接口编写人员')),
                ('Api_request', models.TextField(verbose_name='接口信息')),
                ('belong_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiManager.ModuleInfo')),
            ],
            options={
                'verbose_name': '接口信息',
                'db_table': 'ApiInfo',
            },
        ),
    ]
