# Generated by Django 2.0.7 on 2020-01-20 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiManager', '0002_apiinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apiinfo',
            old_name='Api_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='apiinfo',
            old_name='Api_include',
            new_name='include',
        ),
        migrations.RenameField(
            model_name='apiinfo',
            old_name='Api_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='apiinfo',
            old_name='Api_request',
            new_name='request',
        ),
        migrations.RenameField(
            model_name='apiinfo',
            old_name='Api_type',
            new_name='type',
        ),
    ]
